// Generated by CoffeeScript 1.7.1
(function() {
  var draw, g;

  g = this;

  $(function() {
    g.today = moment();
    if (QueryString.year) {
      g.today = g.today.year(QueryString.year);
    }
    if (QueryString.month) {
      g.today = g.today.month(QueryString.month - 1);
    }
    draw();
    $('#next').click(function() {
      g.today = g.today.add(1, 'M');
      return draw();
    });
    return $('#prev').click(function() {
      if (g.today.format('YYMM') === '1501') {
        window.location = 'dec2014.php';
      }
      g.today = g.today.subtract(1, 'M');
      return draw();
    });
  });

  draw = function() {
    var eom, i, _i, _ref, _results;
    $('.first:gt(0)').remove();
    eom = g.today.date(1).add(1, 'M').subtract(1, 'd');
    $('#month').html(g.today.format('MMMM'));
    $('#year').html(g.today.format('YYYY'));
    _results = [];
    for (i = _i = 1, _ref = eom.date(); 1 <= _ref ? _i <= _ref : _i >= _ref; i = 1 <= _ref ? ++_i : --_i) {
      _results.push((function(i) {
        var d, day, row, s;
        row = $('.first:eq(0)').clone();
        row.find('td').html('');
        row.show();
        d = g.today.date(i);
        day = ((i - 1) % 7) + 1;
        if (d.day() === 0 || i === 1) {
          $('#calendar').append(row);
        }
        s = (function() {
          switch (d.day()) {
            case 3:
              return i + ("<p><a href='results/" + (d.format('YYMMDD') + 'E.htm') + "'>Results</a></p>");
            case 4:
              return i + ("<p><a href='results/" + (d.format('YYMMDD') + 'A.htm') + "'>Results</a></p>");
            case 5:
              return i + ("<p><a href='results/" + (d.format('YYMMDD') + 'M.htm') + "'>Results</a></p>");
            default:
              return i;
          }
        })();
        return $('#calendar tr:last').find("td:eq(" + (d.day()) + ")").html(s);
      })(i));
    }
    return _results;
  };

}).call(this);
